# Generated by Django 5.1.1 on 2024-09-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=128, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "hobbies",
                    models.TextField(blank=True, null=True, verbose_name="Hobbies"),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False, verbose_name="Is email verified"
                    ),
                ),
                (
                    "is_phone_number_verified",
                    models.BooleanField(
                        default=False, verbose_name="Is phone number verified"
                    ),
                ),
            ],
        ),
    ]
